# Generated by Django 2.0.2 on 2018-03-08 04:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state_id', models.IntegerField()),
            ],
            options={
                'db_table': 'data_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 417504))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 417524))),
            ],
            options={
                'db_table': '_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country_id', models.IntegerField()),
            ],
            options={
                'db_table': 'data_states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.TextField()),
                ('email', models.CharField(max_length=30, unique=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 421122))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 421139))),
                ('role', models.TextField()),
            ],
            options={
                'db_table': 'data_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 415490))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 415526))),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 415554))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 415569))),
            ],
            options={
                'db_table': 'data_advertisement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('avatar', models.FileField(upload_to='advertiser/')),
                ('company_name', models.TextField()),
                ('company_address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 416260))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 416276))),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.User')),
            ],
            options={
                'db_table': 'data_advertiser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('street', models.TextField()),
                ('area', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 416789))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 416805))),
            ],
            options={
                'db_table': 'data_board',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('service_tax_ratio', models.FloatField()),
                ('service_tax', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('token', models.TextField()),
                ('transaction_type', models.TextField()),
                ('pay_log', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 418016))),
                ('advertiser', models.ForeignKey(db_column='Advertiser_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Advertiser')),
            ],
            options={
                'db_table': 'data_payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('avatar', models.FileField(upload_to='publisher/')),
                ('company_name', models.TextField()),
                ('company_address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 418595))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 418611))),
                ('user', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.User')),
            ],
            options={
                'db_table': 'data_publisher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requestboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 419039))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 419061))),
                ('request_status', models.SmallIntegerField(blank=True, null=True)),
                ('approve_status', models.SmallIntegerField(blank=True, null=True)),
                ('shown', models.SmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(db_column='Advertiser_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Advertiser')),
                ('board', models.ForeignKey(db_column='Board_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Board')),
                ('publisher', models.ForeignKey(db_column='Publisher_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Publisher')),
            ],
            options={
                'db_table': 'data_requestboard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field', models.TimeField(db_column='from_')),
                ('to', models.TimeField()),
                ('total', models.IntegerField()),
                ('slot_price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 419784))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 419800))),
                ('board', models.ForeignKey(db_column='Board_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Board')),
                ('publisher', models.ForeignKey(db_column='Publisher_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Publisher')),
            ],
            options={
                'db_table': 'data_slot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('location', models.FileField(upload_to='advertisement/')),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 420584))),
                ('current_state', models.IntegerField()),
                ('seconds', models.BigIntegerField()),
                ('upload_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 420621))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 3, 8, 4, 29, 43, 420635))),
                ('advertiser', models.ForeignKey(db_column='Advertiser_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Advertiser')),
            ],
            options={
                'db_table': 'data_upload',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='requestboard',
            name='slot',
            field=models.ForeignKey(db_column='Slot_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Slot'),
        ),
        migrations.AddField(
            model_name='payment',
            name='publisher',
            field=models.ForeignKey(db_column='Publisher_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Publisher'),
        ),
        migrations.AddField(
            model_name='payment',
            name='slot',
            field=models.ForeignKey(db_column='Slot_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Slot'),
        ),
        migrations.AddField(
            model_name='board',
            name='publisher',
            field=models.ForeignKey(db_column='Publisher_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Publisher'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertiser',
            field=models.ForeignKey(db_column='Advertiser_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Advertiser'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='board',
            field=models.ForeignKey(db_column='Board_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Board'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='slot',
            field=models.ForeignKey(db_column='Slot_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Slot'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='upload',
            field=models.ForeignKey(db_column='Upload_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.Upload'),
        ),
    ]
